### PR TITLE
Deploy to gh-pages

### LINKED ISSUE #14: Publish app online
Eg. using gh-pages or S3.

### PR DESCRIPTION
**Pull request by hamishtaplin**
Fixes #14.

Adds deploy scripts using `yarn deploy`.

https://medium.freecodecamp.com/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089#.wtuzwpp15

### CODE REVIEW

**Comment by hamishtaplin** [comment]
Worth adding a post-merge hook to do this automagically when merged into master?

**Comment by samiwel** [comment]
Wow, can't believe it's that simple to deploy to gh-pages.

**Comment by hamishtaplin** [comment]
I have no idea how to implement that as it would need `yarn deploy` to be run somewhere the app can be built/deployed.

**Comment by samiwel** [comment]
Let's merge this and we can look at the post-merge hook in another PR?

**Pull request merged**
